# version: "3.9"

networks:
  transcendence:
    name: transcendence
    driver: bridge

services:
  user_management:
    image: user_management
    container_name: user_management
    build:
      context: .
      dockerfile: user_management/Dockerfile
    depends_on:
      - db_user_management
    networks:
      - transcendence
    init: true

  db_user_management:
    image: postgres:15
    restart: always
    container_name: db_user_management
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-django}
      POSTGRES_DB: db_user_management
    volumes:
      - test_postgres_user_management:/var/lib/postgresql/data
    networks:
      - transcendence

  chat:
    image: chat
    container_name: chat
    build:
      context: .
      dockerfile: chat/Dockerfile
    volumes:
      - ./chat:/workspace/chat
    depends_on:
      - user_management
      - db_chat
    networks:
      - transcendence

  db_chat:
    container_name: db_chat
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-django}
      POSTGRES_DB: db_chat
    volumes:
      - test_postgres_chat:/var/lib/postgresql/data
    networks:
      - transcendence

  friends_list:
    image: friends_list
    container_name: friends_list
    build:
      context: .
      dockerfile: friends_list/Dockerfile
    volumes:
      - ./friends_list:/workspace/friends_list
    depends_on:
      - db_friends_list
      - user_management
    networks:
      - transcendence
    init: true

  db_friends_list:
    container_name: db_friends_list
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-django}
      POSTGRES_DB: db_friends_list
    volumes:
      - test_postgres_friends_list:/var/lib/postgresql/data
    networks:
      - transcendence

  redis:
    container_name: redis
    image: redis
    restart: always
    networks:
      - transcendence

  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - user_management
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    networks:
      - transcendence
    ports:
      - "5000:443"
    restart: unless-stopped
    init: true

  avatar:
    image: avatar
    container_name: avatar
    build:
      context: .
      dockerfile: avatar/Dockerfile
    volumes:
      - test_images_volume:/avatar_images/images
    networks:
      - transcendence
    ports:
      - 8000:8000
    init: true

  db_avatar:
    image: postgres:15
    restart: always
    container_name: db_avatar
    environment:
      POSTGRES_USER: avatar
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-avatar}
      POSTGRES_DB: db_avatar
    volumes:
      - test_postgres_avatar:/var/lib/postgresql/data
    networks:
      - transcendence
volumes:
  test_postgres_user_management:
    name: test_postgres_user_management
  test_postgres_chat:
    name: test_postgres_chat
  test_postgres_friends_list:
    name: test_postgres_friends_list
  test_postgres_avatar:
    name: test_postgres_avatar
  test_images_volume:
    name: test_images_volume
