# Generated by Django 5.1.3 on 2024-11-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(blank=True, max_length=100, null=True)),
                ('ball_x', models.FloatField(default=0.5)),
                ('ball_y', models.FloatField(default=0.5)),
                ('paddle1_y', models.FloatField(default=0.5)),
                ('paddle2_y', models.FloatField(default=0.5)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
