# Generated by Django 4.2.16 on 2024-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_how_are_you'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='how_are_you',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
